### ISSUE TITLE
Hello, may I ask if 'sensor.camera.huawei_fisheye' is a custom fisheye camera model defined in Unreal Engine?How can I obtain a version of CARLA that includes the 'sensor.camera.huawei_fisheye'?

### ISSUE THREAD

**Issue by StoneZ7** [LadissonLai/BEV-Dataset-collector#2]
bp_fisheye = blueprint_library.find('sensor.camera.huawei_fisheye')
        bp_fisheye.set_attribute('image_size_x', str(1920))
        bp_fisheye.set_attribute('image_size_y', str(1080))

**Comment by LadissonLai** [comment]
> bp_fisheye = blueprint_library.find('sensor.camera.huawei_fisheye') bp_fisheye.set_attribute('image_size_x', str(1920)) bp_fisheye.set_attribute('image_size_y', str(1080))

Sorry, the version of CARLA (a customed version not in UE) currently is not open source. You can just use the pre-build version.

**Comment by yaoweixiao-ux** [comment]
Same Problem
