### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by MrChaa** [LadissonLai/BEV-Dataset-collector#3]
Hello, the parking garage you build is impressive, is there any reference on how to build a parking garage in Carla? Thanks

**Comment by LadissonLai** [comment]
> Hello, the parking garage you build is impressive, is there any reference on how to build a parking garage in Carla? Thanks

Thank you for your question. This building process is like any CG modeling process.  You could refer to the carla [office document](https://carla.readthedocs.io/en/0.9.15/tuto_content_authoring_maps/) about custom map using **RoadRunner** and **UE**.
